/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#95d3ba',
        'outline': '#707974',
        'surface-container': '#edeeef',
        'on-background': '#191c1d',
        'error': '#ba1a1a',
        'surface-tint': '#2b6954',
        'secondary-fixed': '#ffdcc3',
        'primary-container': '#064e3b',
        'on-tertiary-fixed': '#141b2b',
        'on-primary-container': '#80bea6',
        'secondary-fixed-dim': '#ffb77d',
        'inverse-primary': '#95d3ba',
        'surface': '#f8f9fa',
        'outline-variant': '#bfc9c3',
        'background': '#f8f9fa',
        'on-tertiary-container': '#aab1c5',
        'inverse-surface': '#2e3132',
        'secondary': '#904d00',
        'on-tertiary-fixed-variant': '#404758',
        'on-surface': '#191c1d',
        'on-secondary-fixed-variant': '#6e3900',
        'surface-container-lowest': '#ffffff',
        'primary': '#003527',
        'primary-fixed': '#b0f0d6',
        'error-container': '#ffdad6',
        'surface-bright': '#f8f9fa',
        'on-secondary-container': '#663500',
        'on-primary-fixed': '#002117',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-low': '#f3f4f5',
        'surface-container-highest': '#e1e3e4',
        'tertiary': '#272e3e',
        'secondary-container': '#fe932c',
        'on-primary-fixed-variant': '#0b513d',
        'surface-container-high': '#e7e8e9',
        'on-error-container': '#93000a',
        'surface-dim': '#d9dadb',
        'on-surface-variant': '#404944',
        'on-secondary-fixed': '#2f1500',
        'surface-variant': '#e1e3e4',
        'tertiary-container': '#3d4455',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#dce2f7',
        'tertiary-fixed-dim': '#c0c6db',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '8px',
        'container-max': '1200px',
        'margin-mobile': '20px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'stack-sm': '12px',
        'margin-desktop': '64px',
        gutter: '24px',
      },
      fontFamily: {
        'display-lg': ['Playfair Display', 'serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}
